package viwer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author henri
 */
public class DialogCadAcai extends javax.swing.JDialog {

    /**
     * Creates new form DialogCadAcai
     */
    public DialogCadAcai(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadAcai = new javax.swing.JPanel();
        jLabelCadAcai = new javax.swing.JLabel();
        jComboBoxTam = new javax.swing.JComboBox<>();
        jButtonCadastrarAcai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListFrutas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jPanelAcompanhamentos = new javax.swing.JPanel();
        jCheckBoxPacoca = new javax.swing.JCheckBox();
        jCheckBoxAmendoim = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBoxLeiteEmPo = new javax.swing.JCheckBox();
        jCheckBoxLeiteCondensado = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Açaí");

        jPanelCadAcai.setBackground(new java.awt.Color(153, 0, 153));

        jLabelCadAcai.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCadAcai.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadAcai.setText("Cadastro de Açaí");

        javax.swing.GroupLayout jPanelCadAcaiLayout = new javax.swing.GroupLayout(jPanelCadAcai);
        jPanelCadAcai.setLayout(jPanelCadAcaiLayout);
        jPanelCadAcaiLayout.setHorizontalGroup(
            jPanelCadAcaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadAcaiLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabelCadAcai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadAcaiLayout.setVerticalGroup(
            jPanelCadAcaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadAcaiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCadAcai)
                .addGap(14, 14, 14))
        );

        jComboBoxTam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tamanho", "300 ml", "500 ml", "750 ml", "1 L" }));
        jComboBoxTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTamActionPerformed(evt);
            }
        });

        jButtonCadastrarAcai.setBackground(new java.awt.Color(153, 153, 153));
        jButtonCadastrarAcai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCadastrarAcai.setText("Cadastrar");
        jButtonCadastrarAcai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarAcaiActionPerformed(evt);
            }
        });

        jListFrutas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Morango", "Banana", "Kiwi", "Manga", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListFrutas);

        jLabel1.setText("Frutas");

        jPanelAcompanhamentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Acompanhamentos"));

        jCheckBoxPacoca.setText("Paçoca");

        jCheckBoxAmendoim.setText("Amendoim");

        jCheckBox3.setText("Biscoito");

        jCheckBoxLeiteEmPo.setText("Leite em pó");

        jCheckBoxLeiteCondensado.setText("Leite Condensado");

        jCheckBox6.setText("Disquete");

        jCheckBox7.setText("Chocolate");

        jCheckBox8.setText("Granola");

        javax.swing.GroupLayout jPanelAcompanhamentosLayout = new javax.swing.GroupLayout(jPanelAcompanhamentos);
        jPanelAcompanhamentos.setLayout(jPanelAcompanhamentosLayout);
        jPanelAcompanhamentosLayout.setHorizontalGroup(
            jPanelAcompanhamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcompanhamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAcompanhamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAcompanhamentosLayout.createSequentialGroup()
                        .addComponent(jCheckBoxPacoca, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxLeiteEmPo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAcompanhamentosLayout.createSequentialGroup()
                        .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAcompanhamentosLayout.createSequentialGroup()
                        .addComponent(jCheckBoxAmendoim, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxLeiteCondensado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAcompanhamentosLayout.createSequentialGroup()
                        .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelAcompanhamentosLayout.setVerticalGroup(
            jPanelAcompanhamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcompanhamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAcompanhamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxPacoca)
                    .addComponent(jCheckBoxLeiteEmPo))
                .addGap(18, 18, 18)
                .addGroup(jPanelAcompanhamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxLeiteCondensado)
                    .addComponent(jCheckBoxAmendoim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanelAcompanhamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox3))
                .addGap(18, 18, 18)
                .addGroup(jPanelAcompanhamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox8)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadAcai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTam, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrarAcai, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanelAcompanhamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCadAcai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxTam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelAcompanhamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jButtonCadastrarAcai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTamActionPerformed

    private void jButtonCadastrarAcaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarAcaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastrarAcaiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarAcai;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBoxAmendoim;
    private javax.swing.JCheckBox jCheckBoxLeiteCondensado;
    private javax.swing.JCheckBox jCheckBoxLeiteEmPo;
    private javax.swing.JCheckBox jCheckBoxPacoca;
    private javax.swing.JComboBox<String> jComboBoxTam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCadAcai;
    private javax.swing.JList<String> jListFrutas;
    private javax.swing.JPanel jPanelAcompanhamentos;
    private javax.swing.JPanel jPanelCadAcai;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
